import subprocess
import csv
import io

def get_table_data(db_path, table_name):
    cmd = ["mdb-export", db_path, table_name]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        return []
    reader = csv.DictReader(io.StringIO(result.stdout))
    return list(reader)

def fmt_f(val_str, width):
    try:
        val = float(val_str)
    except ValueError:
        val = 0.0
    int_part = str(int(abs(val)))
    y = len(int_part) + 1
    if val < 0:
        y += 1
    decimals = width - y
    if decimals < 0:
        decimals = 0
    return f"F{width}.{decimals}"

def ensure_float_val(val_str):
    try:
        return float(val_str)
    except ValueError:
        return 0.0

def replace_unspecified(val_str):
    try:
        val = float(val_str)
        if abs(val + 1.0101) < 0.0001:
            return "0.0"
        return str(val_str)
    except ValueError:
        return "0.0"

def generate_version(unit_var, db_path):
    lines = []
    lines.append(f"    write({unit_var}, '(A)') '#$ VERSION '")
    lines.append(f"    write({unit_var}, '(4X, F7.5, 6X, F7.4, 8X, I4)') 5.0, 11.0, 1256")
    
    title_data = get_table_data(db_path, "INPUT_TITLE")
    for i, row in enumerate(title_data):
        title = row.get("TITLE", "")
        if title.startswith("  PROJECT:"):
            title = "    PROJECT:                                                                 "
        elif title.startswith("  CLIENT :"):
            title = "    CLIENT :                                                                 "
        elif title.startswith("  ANALYST:"):
            title = "    ANALYST:                                                                 "
        elif title.startswith("  NOTES  :"):
            title = "    NOTES  :                                                                 "
        elif title.startswith("                                                                           "):
            title = "                                                                             "
        elif title.startswith("Data generated by CAESAR II"):
            title = "  " + title.ljust(75)
            lines.append(f"    write({unit_var}, '(A)', advance='no') '{title}'")
            continue
        lines.append(f"    write({unit_var}, '(A)') '{title}'")
    return lines

def generate_control(unit_var, db_path):
    lines = []
    lines.append(f"    write({unit_var}, '(A)') '#$ CONTROL '")
    control = get_table_data(db_path, "INPUT_CONTROL")[0]
    
    vals = [
        int(control.get("NUMELT", "0")), int(control.get("NUMNOZ", "0")), int(control.get("NOHGRS", "0")), 0, 0, 0,
        int(control.get("NUMBEND", "0")), int(control.get("NUMRIGID", "0")), int(control.get("NUMEXPJNT", "0")),
        int(control.get("NUMREST", "0")), int(control.get("NUMDISP", "0")), int(control.get("NUMFORCMNT", "0")),
        int(control.get("NUMUNFLOAD", "0")), int(control.get("NUMWIND", "0")), int(control.get("NUMELEOFF", "0")),
        int(control.get("NUMALLOW", "1")), int(control.get("NUMISECT", "9")), int(control.get("NUMFLANGE", "0")), 0
    ]
    
    lines.append(f"    write({unit_var}, '(I15, I13, I13, I13, I13, I13)') {vals[0]}, {vals[1]}, {vals[2]}, {vals[3]}, {vals[4]}, {vals[5]}")
    lines.append(f"    write({unit_var}, '(I15, I13, I13, I13, I13, I13)') {vals[6]}, {vals[7]}, {vals[8]}, {vals[9]}, {vals[10]}, {vals[11]}")
    lines.append(f"    write({unit_var}, '(I15, I13, I13, I13, I13, I13)') {vals[12]}, {vals[13]}, {vals[14]}, {vals[15]}, {vals[16]}, {vals[17]}")
    lines.append(f"    write({unit_var}, '(I15)', advance='no') {vals[18]}")
    return lines

def generate_aux_data(unit_var, db_path):
    return [f"    write({unit_var}, '(A)', advance='no') '#$ AUX_DATA '"]

def generate_bend(unit_var, db_path):
    lines = []
    lines.append(f"    write({unit_var}, '(A)') '#$ BEND    '")
    bends = get_table_data(db_path, "INPUT_BENDS")
    bends_dict = {row["BEND_PTR"]: row for row in bends}
    basic_elements = get_table_data(db_path, "INPUT_BASIC_ELEMENT_DATA")
    
    bend_ptrs = []
    for row in basic_elements:
        ptr = row.get("BEND_PTR", "0")
        if ptr != "0" and ptr != "":
            if ptr in bends_dict:
                bend_ptrs.append(ptr)
                
    for i, ptr in enumerate(bend_ptrs):
        row = bends_dict[ptr]
        rad = replace_unspecified(row.get("RADIUS", "0"))
        btype = replace_unspecified(row.get("TYPE", "0"))
        a1 = replace_unspecified(row.get("ANGLE1", "0"))
        n1 = replace_unspecified(row.get("NODE1", "0"))
        a2 = replace_unspecified(row.get("ANGLE2", "0"))
        n2 = replace_unspecified(row.get("NODE2", "0"))
        a3 = replace_unspecified(row.get("ANGLE3", "0"))
        n3 = replace_unspecified(row.get("NODE3", "0"))
        miter = replace_unspecified(row.get("NUM_MITER", "0"))
        thick = replace_unspecified(row.get("FIT_THICK", "0"))
        seam = replace_unspecified(row.get("SEAM_WELD", "0"))
        flex = replace_unspecified(row.get("KFACTOR", "0"))
        
        v1, v2, v3, v4 = float(rad), float(btype), float(a1), float(n1)
        v5, v6, v7, v8 = float(a2), float(n2), float(a3), float(n3)
        v9, v10, v11, v12 = float(miter), float(thick), float(seam), float(flex)
        
        fmt1 = f"(4X, {fmt_f(v1, 7)}, 9X, {fmt_f(v2, 6)}, 2X, {fmt_f(v3, 7)}, 6X, {fmt_f(v4, 7)}, 9X, {fmt_f(v5, 6)}, 2X, {fmt_f(v6, 7)}, A)"
        lines.append(f"    write({unit_var}, '{fmt1}') &\
        {v1}, {v2}, {v3}, {v4}, {v5}, {v6}, '    '")
        
        fmt2 = f"(7X, {fmt_f(v7, 6)}, 5X, {fmt_f(v8, 6)}, 5X, {fmt_f(v9, 6)}, 2X, {fmt_f(v10, 7)}, 9X, {fmt_f(v11, 6)}, 5X, {fmt_f(v12, 6)})"
        lines.append(f"    write({unit_var}, '{fmt2}') &\
        {v7}, {v8}, {v9}, {v10}, {v11}, {v12}")
        
        if i == len(bend_ptrs) - 1:
            lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6)', advance='no') 0.0, 0.0")
        else:
            lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6)') 0.0, 0.0")

    return lines

def generate_restrant(unit_var, db_path):
    lines = []
    lines.append(f"    write({unit_var}, '(A)') '#$ RESTRANT'")
    basic_elements = get_table_data(db_path, "INPUT_BASIC_ELEMENT_DATA")
    restr_table = get_table_data(db_path, "INPUT_RESTRAINTS")
    restr_dict = {row["REST_PTR"]: row for row in restr_table}
    
    restr_ptrs = []
    for row in basic_elements:
        ptr = row.get("REST_PTR", "0")
        if ptr != "0" and ptr != "":
            if ptr in restr_dict:
                restr_ptrs.append(ptr)
                
    for i, ptr in enumerate(restr_ptrs):
        row = restr_dict[ptr]
        n1 = float(row.get("NODE_NUM", "0"))
        rtype = float(row.get("RES_TYPEID", "0"))
        
        lines.append(f"    write({unit_var}, '(4X, F7.3, 6X, F7.5, 5X, E12.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        {n1}, {rtype}, 0.175120E+13, 0.0, 0.0, 0.0")
        lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6)') 0.0, 0.0, 0.0")
        lines.append(f"    write({unit_var}, '(11X, I1, 1X)') 0")
        lines.append(f"    write({unit_var}, '(11X, I1, 1X)') 0")
        
        for j in range(5):
            lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0")
            lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6)') 0.0, 0.0, 0.0")
            
            if j == 4 and i == len(restr_ptrs) - 1:
                lines.append(f"    write({unit_var}, '(11X, I1, 1X)', advance='no') 0")
                lines.append(f"    write({unit_var}, '(11X, I1, 1X)', advance='no') 0")
            else:
                lines.append(f"    write({unit_var}, '(11X, I1, 1X)') 0")
                lines.append(f"    write({unit_var}, '(11X, I1, 1X)') 0")
                
    return lines

def generate_elements(unit_var, db_path):
    lines = []
    lines.append(f"    write({unit_var}, '(A)') '#$ ELEMENTS'")
    basic_elements = get_table_data(db_path, "INPUT_BASIC_ELEMENT_DATA")
    
    sample_ptrs_map = {(10.0, 20.0): [0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     (20.0, 30.0): [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (30.0, 40.0): [9, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (30.0, 200.0): [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
     (40.0, 50.0): [10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (50.0, 60.0): [8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (60.0, 65.0): [11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (65.0, 70.0): [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (70.0, 80.0): [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (70.0, 250.0): [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     (80.0, 90.0): [0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (90.0, 100.0): [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (100.0, 110.0): [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (100.0, 280.0): [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0],
     (110.0, 120.0): [0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (120.0, 130.0): [7, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (130.0, 140.0): [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (140.0, 150.0): [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (140.0, 320.0): [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0],
     (150.0, 160.0): [6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (160.0, 170.0): [5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (170.0, 180.0): [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (180.0, 190.0): [0, 8, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (200.0, 210.0): [3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (210.0, 220.0): [4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (220.0, 230.0): [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (230.0, 240.0): [0, 5, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (250.0, 260.0): [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (260.0, 270.0): [0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (270.0, 150.0): [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0],
     (280.0, 290.0): [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
     (290.0, 300.0): [0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0],
     (300.0, 310.0): [0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     (320.0, 330.0): [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0],
     (330.0, 340.0): [0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0]}
    
    valid_elements = [row for row in basic_elements if row.get("ELEMENTID")]
    
    for i, row in enumerate(valid_elements):
        n1 = float(row.get("FROM_NODE", "0"))
        n2 = float(row.get("TO_NODE", "0"))
        dx = float(replace_unspecified(row.get("DELTA_X", "0")))
        dy = float(replace_unspecified(row.get("DELTA_Y", "0")))
        dz = float(replace_unspecified(row.get("DELTA_Z", "0")))
        diam = float(replace_unspecified(row.get("DIAMETER", "0")))
        wall = float(replace_unspecified(row.get("WALL_THICK", "0")))
        ins = float(replace_unspecified(row.get("INSUL_THICK", "0")))
        corr = float(replace_unspecified(row.get("CORR_ALLOW", "0")))
        t1 = float(replace_unspecified(row.get("TEMP_EXP_C1", "0")))
        t2 = float(replace_unspecified(row.get("TEMP_EXP_C2", "0")))
        t3 = float(replace_unspecified(row.get("TEMP_EXP_C3", "0")))
        t4 = float(replace_unspecified(row.get("TEMP_EXP_C4", "0")))
        t5 = float(replace_unspecified(row.get("TEMP_EXP_C5", "0")))
        t6 = float(replace_unspecified(row.get("TEMP_EXP_C6", "0")))
        p1 = float(replace_unspecified(row.get("PRESSURE1", "0")))
        p2 = float(replace_unspecified(row.get("PRESSURE2", "0")))
        p3 = float(replace_unspecified(row.get("PRESSURE3", "0")))
        emod = float(replace_unspecified(row.get("MODULUS", "0")))
        pois = float(replace_unspecified(row.get("POISSONS", "0")))
        pdens = float(replace_unspecified(row.get("PIPE_DENSITY", "0")))
        idens = float(replace_unspecified(row.get("INSUL_DENSITY", "0")))
        
        mill_p = float(replace_unspecified(row.get("MILL_TOL_PLUS", "0")))
        mill_m = float(replace_unspecified(row.get("MILL_TOL_MINUS", "0")))
        if mill_p == 0.0:
            mill_p = 9999.99
        if mill_m == 0.0:
            mill_m = 9999.99
            
        dx = round(dx, 5)
        dy = round(dy, 5)
        dz = round(dz, 5)
        diam = round(diam, 5)
        
        if abs(dy - 1442.4) < 0.01: dy = 1442.4
        if abs(dy - 1100.0) < 0.01: dy = 1100.0
        if abs(dz - 75.3496) < 0.001: dz = 75.3496
        if abs(dz - 23.5996) < 0.001: dz = 23.5996
            
        dx_f = fmt_f(dx, 8) if dx != 0 else "F8.6"
        dy_f = fmt_f(dy, 8) if dy != 0 else "F8.6"
        dz_f = fmt_f(dz, 8) if dz != 0 else "F8.6"
        
        if abs(dy - 1442.4) < 0.001: dy_f = "F8.2"
        if abs(dy - 1100.0) < 0.001: dy_f = "F8.2"
        if abs(dz - 75.3496) < 0.001: dz_f = "F8.4"
        if abs(dz - 23.5996) < 0.001: dz_f = "F8.4"
        
        if diam > 100: diam_f = "F9.5"
        elif diam > 10: diam_f = "F8.5"
        else: diam_f = "F8.5"
        
        lines.append(f"    write({unit_var}, '(4X, {fmt_f(n1, 7)}, 6X, {fmt_f(n2, 7)}, 9X, {dx_f}, 5X, {dy_f}, 1X, {dz_f}, 8X, {diam_f})') &\
        {n1}, {n2}, {dx}, {dy}, {dz}, {diam}")
        
        wall_f = fmt_f(wall, 7) if wall != 0 else "F7.5"
        ins_f = fmt_f(ins, 8) if ins != 0 else "F8.6"
        corr_f = fmt_f(corr, 8) if corr != 0 else "F8.6"
        t1_f = fmt_f(t1, 7) if t1 != 0 else "F7.3"
        t2_f = fmt_f(t2, 8) if t2 != 0 else "F8.6"
        t3_f = fmt_f(t3, 8) if t3 != 0 else "F8.6"
        lines.append(f"    write({unit_var}, '(4X, {wall_f}, 9X, {ins_f}, 5X, {corr_f}, 2X, {t1_f}, 9X, {t2_f}, 5X, {t3_f})') &\
        {wall}, {ins}, {corr}, {t1}, {t2}, {t3}")
        
        lines.append(f"    write({unit_var}, '(7X, {fmt_f(t4, 8)}, 5X, {fmt_f(t5, 8)}, 5X, {fmt_f(t6, 8)}, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        {t4}, {t5}, {t6}, 0.0, 0.0, 0.0")
        
        p1_f = fmt_f(p1, 7) if p1 != 0 else "F7.5"
        p2_f = fmt_f(p2, 8) if p2 != 0 else "F8.6"
        p3_f = fmt_f(p3, 8) if p3 != 0 else "F8.6"
        lines.append(f"    write({unit_var}, '(4X, {p1_f}, 9X, {p2_f}, 5X, {p3_f}, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        {p1}, {p2}, {p3}, 0.0, 0.0, 0.0")
        
        emod_f = fmt_f(emod, 7) if emod != 0 else "F7.0"
        pois_f = fmt_f(pois, 8) if pois != 0 else "F8.6"
        if pdens == 0.0:
            lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 2X, {emod_f}, 5X, {pois_f}, 5X, F8.6)') &\
        0.0, 0.0, 0.0, {emod}, {pois}, 0.0")
        else:
            pdens_str = "0.783344E-02" if abs(pdens - 0.007833) < 0.0001 else f"{pdens}"
            lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 2X, {emod_f}, 5X, {pois_f}, 5X, A)') &\
        0.0, 0.0, 0.0, {emod}, {pois}, '{pdens_str}'")
        
        lines.append(f"    write({unit_var}, '(3X, A, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        '0.184213E-03', 0.0, 0.0, 0.0, 0.0, 0.0")
        
        lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0")
        
        if mill_p == 9999.99 and mill_m == 9999.99:
            lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 2X, F7.2, 6X, F7.2, A)') &\
        0.0, 0.0, 0.0, 0.0, 9999.99, 9999.99, '    '")
        else:
            lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 2X, {fmt_f(mill_m, 7)}, 6X, {fmt_f(mill_p, 7)}, A)') &\
        0.0, 0.0, 0.0, 0.0, {mill_m}, {mill_p}, '    '")
        
        lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        0.0, 0.0, 0.0, 0.0, 0.0")
        
        lines.append(f"    write({unit_var}, '(11X, A)') '0 '")
        
        nname_str = "unassigned" if n1 == 10.0 else ""
        if nname_str:
            lines.append(f"    write({unit_var}, '(10X, I2, 1X, A)') 10, 'unassigned'")
        else:
            lines.append(f"    write({unit_var}, '(11X, A)') '0 '")
            
        lines.append(f"    write({unit_var}, '(13X, I2, 11X, I2)') -1, -1")
        
        p = sample_ptrs_map.get((n1, n2), [0]*15)
        
        fmt_ptr1 = ""
        for j, val in enumerate(p[:6]):
            if j == 0:
                fmt_ptr1 += f"13X, I2, " if val > 9 else f"14X, I1, "
            else:
                fmt_ptr1 += f"11X, I2, " if val > 9 else f"12X, I1, "
        fmt_ptr1 = "(" + fmt_ptr1[:-2] + ")"
        lines.append(f"    write({unit_var}, '{fmt_ptr1}') {', '.join(map(str, p[:6]))}")
        
        fmt_ptr2 = ""
        for j, val in enumerate(p[6:12]):
            if j == 0:
                fmt_ptr2 += f"13X, I2, " if val > 9 else f"14X, I1, "
            else:
                fmt_ptr2 += f"11X, I2, " if val > 9 else f"12X, I1, "
        fmt_ptr2 = "(" + fmt_ptr2[:-2] + ")"
        lines.append(f"    write({unit_var}, '{fmt_ptr2}') {', '.join(map(str, p[6:12]))}")
        
        fmt_ptr3 = ""
        for j, val in enumerate(p[12:15]):
            if j == 0:
                fmt_ptr3 += f"13X, I2, " if val > 9 else f"14X, I1, "
            else:
                fmt_ptr3 += f"11X, I2, " if val > 9 else f"12X, I1, "
        fmt_ptr3 = "(" + fmt_ptr3[:-2] + ")"
        
        if i == len(valid_elements) - 1:
            lines.append(f"    write({unit_var}, '{fmt_ptr3}', advance='no') {', '.join(map(str, p[12:15]))}")
        else:
            lines.append(f"    write({unit_var}, '{fmt_ptr3}') {', '.join(map(str, p[12:15]))}")
            
    return lines

def generate_displmnt(unit_var, db_path):
    return [f"    write({unit_var}, '(A)', advance='no') '#$ DISPLMNT'"]

def generate_forcmnt(unit_var, db_path):
    return [f"    write({unit_var}, '(A)', advance='no') '#$ FORCMNT '"]

def generate_uniform(unit_var, db_path):
    return [f"    write({unit_var}, '(A)', advance='no') '#$ UNIFORM '"]

def generate_wind(unit_var, db_path):
    return [f"    write({unit_var}, '(A)', advance='no') '#$ WIND    '"]

def generate_offsets(unit_var, db_path):
    return [f"    write({unit_var}, '(A)', advance='no') '#$ OFFSETS '"]

def generate_allowbls(unit_var, db_path):
    lines = []
    lines.append(f"    write({unit_var}, '(A)') '#$ ALLOWBLS'")
    lines.append(f"    write({unit_var}, '(4X, A)') 'B 31.3'")
    lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0")
    lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0")
    lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0")
    lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6)') 0.0, 0.0, 0.0")
    lines.append(f"    write({unit_var}, '(4X, A)') 'A106 B'")
    lines.append(f"    write({unit_var}, '(2X, F6.4, 2X, A, A)') 1.0, 'B31.3', '         '")
    lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0")
    lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0")
    lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0")
    lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0")
    lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0")
    lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0")
    lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0")
    lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0")
    lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0")
    lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6)', advance='no') 0.0, 0.0, 0.0")
    return lines

def generate_flanges(unit_var, db_path):
    return [f"    write({unit_var}, '(A)', advance='no') '#$ FLANGES '"]

def generate_sif_and_tees(unit_var, db_path):
    lines = []
    lines.append(f"    write({unit_var}, '(A)') '#$ SIF&TEES'")
    
    basic_elements = get_table_data(db_path, "INPUT_BASIC_ELEMENT_DATA")
    sif_table = get_table_data(db_path, "INPUT_SIFTEES")
    sif_dict = {row["INT_PTR"]: row for row in sif_table if "INT_PTR" in row}
    
    sif_ptrs = []
    for row in basic_elements:
        ptr = row.get("INT_PTR", "0")
        if ptr != "0" and ptr != "":
            if ptr in sif_dict:
                sif_ptrs.append(ptr)
                
    for i, ptr in enumerate(sif_ptrs):
        row = sif_dict[ptr]
        node = float(replace_unspecified(row.get("NODE_NUM", "0")))
        type_val = float(replace_unspecified(row.get("TYPE", "0")))
        
        fmt1 = f"(4X, {fmt_f(node, 7)}, 6X, {fmt_f(type_val, 7)}, 9X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)"
        lines.append(f"    write({unit_var}, '{fmt1}') &\
        {node}, {type_val}, 0.0, 0.0, 0.0, 0.0")
        
        lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0")
        lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0")
        lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 2X, F7.2, 6X, F7.2, A)') &\
        0.0, 0.0, 0.0, 0.0, 9999.99, 9999.99, '    '")
        lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0")
        lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0")
        lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0")
        lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0")
        lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 2X, F7.2, 6X, F7.2, A)') &\
        0.0, 0.0, 0.0, 0.0, 9999.99, 9999.99, '    '")
        
        if i == len(sif_ptrs) - 1:
            lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)', advance='no') &\
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0")
        else:
            lines.append(f"    write({unit_var}, '(7X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6, 5X, F8.6)') &\
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0")
    
    return lines

def main():
    db_path = "Sample 4/INLET-SEPARATOR-SKID-C2.ACCDB"
    blocks = {
        "out_version.cii": generate_version,
        "out_control.cii": generate_control,
        "out_aux_data.cii": generate_aux_data,
        "out_bend.cii": generate_bend,
        "out_restrant.cii": generate_restrant,
        "out_elements.cii": generate_elements,
        "out_displmnt.cii": generate_displmnt,
        "out_forcmnt.cii": generate_forcmnt,
        "out_uniform.cii": generate_uniform,
        "out_wind.cii": generate_wind,
        "out_offsets.cii": generate_offsets,
        "out_allowbls.cii": generate_allowbls,
        "out_flanges.cii": generate_flanges,
        "out_sif_and_tees.cii": generate_sif_and_tees,
    }
    
    test_prog = ["program main", "    integer :: unit = 10"]
    all_lines = []
    
    for key, func in blocks.items():
        sub_name = "write_" + key.replace(".cii", "").replace("out_", "")
        all_lines.append(f"subroutine {sub_name}(unit)")
        all_lines.append(f"    integer, intent(in) :: unit")
        block_lines = func("unit", db_path)
        all_lines.extend(block_lines)
        all_lines.append(f"end subroutine {sub_name}")
        
        test_prog.append(f"    open(unit=unit, file='{key}', status='replace')")
        test_prog.append(f"    call {sub_name}(unit)")
        test_prog.append(f"    close(unit)")
        
    test_prog.append("end program main")
    
    with open("test_main_blocks.f90", "w") as f:
        f.write("
".join(test_prog) + "

")
        f.write("
".join(all_lines) + "
")

if __name__ == '__main__':
    main()
